### ISSUE TITLE
Rendering artefact

### ISSUE THREAD

**Issue by rurseekatze** [rurseekatze/node-tileserver#11]
Fix a bug that causes rendering artefacts. In every known case a lines goes either from the top left corner parallel to the tile bound or from the top left corner to the bottom right corner of a tile.

The bug can be seen on the map of the [OpenRailwayMap](https://github.com/rurseekatze/OpenRailwayMap) project (which uses node-tileserver for rendering):

![1](https://cloud.githubusercontent.com/assets/931928/3879719/bc21801a-217b-11e4-9844-0622c1998834.png)

![1](https://camo.githubusercontent.com/e962a8723edbc4f71b44dfbb0ee16e78dd74bf32/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f353832313335362f313434343639302f61646430316636342d343230652d313165332d383263302d3733313638636135333561612e504e47)

**Comment by neiljp** [comment]
Another strange diagonal rendering bug here (though less close to 45 degrees than that above):
![screenshot 2](https://cloud.githubusercontent.com/assets/9568999/5858650/c1471f08-a24c-11e4-9d72-20bee8aec145.png)

**Comment by neiljp** [comment]
Also see here near Christchurch, horizontal orange line (primarily):
![screenshot 3](https://cloud.githubusercontent.com/assets/9568999/5858748/7d72edd8-a24d-11e4-9ae0-41d093dfa8d1.png)
Zoomed in, part of the artifact is retained, as the bridge (?) appears to be rendered with 'spikes' to the left and right, above and below the orange line:
![screenshot 4](https://cloud.githubusercontent.com/assets/9568999/5858766/99f70cd2-a24d-11e4-8c4d-3e3163d74292.png)

**Comment by neiljp** [comment]
Not sure if this bug is related, but it changes on different zoom levels (the Peterborough one does too). For example, at this zoom level a large chunk of the map is either absent or rendered very differently, between Brentwood and Woodford (top), and west of Sidcup to Northfleet (bottom). Going to this area and zooming in shows all the lines, and zooming out shows the non-black lines.
![screenshot 6](https://cloud.githubusercontent.com/assets/9568999/5859205/7bbf5b18-a250-11e4-8f85-2029e67959d4.png)

**Comment by DerDakon** [comment]
![rendering_error](https://cloud.githubusercontent.com/assets/10909049/7735513/fda8bc1a-ff3d-11e4-89f6-13f99898dd76.png)

**Comment by DerDakon** [comment]
![328](https://cloud.githubusercontent.com/assets/10909049/7868773/818465b6-057e-11e5-8190-c253cd39de95.png)
![canvas](https://cloud.githubusercontent.com/assets/10909049/7868774/818c9c7c-057e-11e5-8954-74a862f28191.png)

Interestingly the bug shows up differently in prerendered and when rendered in browser, so this smells for me like using an uninitialized variable.

**Comment by DerDakon** [comment]
When we once looked into this there always were line segments from the data that ended exactly at the tile border.
