### ISSUE TITLE
900913 vs. 3857

### ISSUE THREAD

**Issue by Nakaner** [rurseekatze/node-tileserver#122]
node-tileserver currently works with EPGS:900913 while current osm2pgsql versions use EPSG:3857.

To do:
- [ ] add a config option to set SRID (but only support 900913 and 3857 as a first step)
- [x] replace 900913 by 3857
- [x] remove osm2pgsql/900913.sql from setup instructions. This file has been removed a few weeks/months ago from osm2pgsql

**Comment by rurseekatze** [comment]
900913 was removed from setup instructions in https://github.com/rurseekatze/node-tileserver/commit/b4c1220aa31abbf92d2d97788cb72fe45bf2011d.

**Comment by Nakaner** [comment]
@rurseekatze wrote:
> 900913 was removed from setup instructions in b4c1220.

That does not help, it makes the situation worse for people who don't know this bug. Please add following line to the setup instructions:

    INSERT INTO spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text)VALUES (900913,'EPSG',900913,'PROJCS["WGS84 / Simple Mercator",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS_1984", 6378137.0, 298.257223563]],PRIMEM["Greenwich", 0.0],UNIT["degree", 0.017453292519943295],AXIS["Longitude", EAST],AXIS["Latitude", NORTH]],PROJECTION["Mercator_1SP_Google"],PARAMETER["latitude_of_origin", 0.0],PARAMETER["central_meridian", 0.0],PARAMETER["scale_factor", 1.0],PARAMETER["false_easting", 0.0],PARAMETER["false_northing", 0.0],UNIT["m", 1.0],AXIS["x", EAST],AXIS["y", NORTH],AUTHORITY["EPSG","900913"]]','+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs');

and tell the readers there that they have to use [`ST_SetSRID(way, 900913)`](http://postgis.net/docs/ST_SetSRID.html) for every table. This workaround might not work if the user wants to apply diffs.

**Comment by rurseekatze** [comment]
With https://github.com/rurseekatze/node-tileserver/commit/b4c1220aa31abbf92d2d97788cb72fe45bf2011d and https://github.com/rurseekatze/node-tileserver/commit/f11f93de2e97a2a3462145244ab9bd7c213324ed, 900913 was completely replaced by 3857.

> add a config option to set SRID (but only support 900913 and 3857 as a first step)

This is not implemented yet. I added a separate issue for this.
