### ISSUE TITLE
All tiles are empty

### ISSUE THREAD

**Issue by SandovalDanilo** [rurseekatze/node-tileserver#129]
Greetings, 

I have configured a running installation of node-tileserver on my own server but all tiles generated are empty. I'm using [this](https://gist.github.com/SandovalDanilo/4791cc919235703290679c16be98e06c) mapcss style and a recently downloaded extract of Berlim from Geofabrik imported via osm2pgsql.

I'm pretty sure I've followed the README correctly and can't seem to find where the problem is.

This is my config.json:

```
{
    "tileSize" : 256,
    "prefix" : "planet_osm",
    "database" : "avm-node",
    "username" : "avm",
    "password" : "",
    "vtiledir" : "./tiles",
    "tiledir" : "./bitmap-tiles",
    "expiredtilesdir" : "./expired-tiles",
    "styledir" : "./styles",
    "zoomOffset" : 0,
    "minZoom" : 0,
    "maxZoom" : 20,
    "styles" : ["default"],
    "intscalefactor" : 10000,
    "geomcolumn" : "way",
    "pxtolerance" : 1.8,
    "maxPrerender" : 8,
    "maxCached" : 16,
    "minExpiring" : 8,
    "maxsockets" : 100,
    "tileserverPort" : 80,
    "tileBoundTolerance" : 60,
    "filterconditions" :
    {
        "0" : ""
    }
}
```

**Comment by Nakaner** [comment]
Hi Sandoval,

just to be sure that you did not tap into one of the common pitfalls:

* Which osm2pgsql style did you use? Just link or post it her.
* Which command did you use to import (one of the options `--latlon` or `--merc`)?
* Which osm2pgsql version did you use?
* Is your database hstore-enabled?
* What's the projection of your database (EPSG:4326, EPSG:3859 or EPSG:900913)? https://github.com/rurseekatze/node-tileserver/issues/122

Best regards

Michael

**Comment by SandovalDanilo** [comment]
Hey Michael,

- The command I used was `osm2pgsql --create --username avm --database avm-node --slim --cache 512 berlin-latest.osm.pbf`, and as it was not defined, the style used was the default and --merc was used. 
- Osm2pgsql version 0.91.0-dev, compiled from the source. 
- Yes, hstore is enabled.
- I'm not sure about the projection, since I didn't see any option about this during the import. As I said, I cloned osm2pgsql from github and compiled it from there. So I assume the default option was used.

Thanks

**Comment by Nakaner** [comment]
> The command I used was `osm2pgsql --create --username avm --database avm-node --slim --cache 512 berlin-latest.osm.pbf`, and as it was not defined, the style used was the default and --merc was used.

`--merc` imports the data as EPSG:3857 which has the same parameters as EPSG:900913 but node-tileserver is such outdated th

> Yes, hstore is enabled.

You have enabled hstore at your database but you did not use it for the import in the correct way. You still have lots of tag columns and one hstore column for tags which do not fit anywhere. node-tileserver expects all tags to be in one single hstore column. You should use your own style sheet which could look like [this](https://github.com/rurseekatze/OpenRailwayMap/blob/master/import/railmap.style).

**Comment by SandovalDanilo** [comment]
> `--merc` imports the data as EPSG:3857 which has the same parameters as EPSG:900913 but node-tileserver is such outdated th

Is this message complete? I think that for some reason the text was cut.

> You have enabled hstore at your database but you did not use it for the import in the correct way. You still have lots of tag columns and one hstore column for tags which do not fit anywhere. node-tileserver expects all tags to be in one single hstore column. You should use your own style sheet which could look like [this](https://github.com/rurseekatze/OpenRailwayMap/blob/master/import/railmap.style).

Ah, I see. So I should be able to configure, using this example, a style to use not only railways but also streets and buildings, right?

**Comment by rurseekatze** [comment]
EPSG:900913 is completely replaced by EPSG:3857. See #122 for further details. Now everything should work properly in your case.

node-tileserver expects all tags in hstore column, so you should configure osm2pgsql so that every tag is at least in the hstore column.

For example, OpenRailwayMap (which uses node-tileserver for rendering) currently runs osm2pgsql with the options `--hstore-all` and `--hstore-match-only` and [this stylefile](https://github.com/rurseekatze/OpenRailwayMap/blob/master/import/openrailwaymap.style) to import only objects with `railway=*` tag and store all tags just in hstore column without creating any separate tag column.

**Comment by michaill** [comment]
I faced the same problems. Problem was in projection, but nothing from hints here was helpful. I solved my problems by using -E 3857 flag in osm2pgsql when importing the pbf data.
