### ISSUE TITLE
MapCSS style example

### ISSUE THREAD

**Issue by am2222** [rurseekatze/node-tileserver#147]
Hi,
Is it possible to share the example of MapCSS style which you are using and works with `map_cssconverter.py` ?
I tried some MapCSSs and they raise errors while I try to convert them. Mostly raise Illegal character for `!` and  `+`

**Comment by DerDakon** [comment]
Look at the [OpenRailwayMap styles](https://github.com/OpenRailwayMap/OpenRailwayMap/tree/master/styles).

**Comment by am2222** [comment]
@DerDakon  Thanks so much
