### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by patrykkalinowski** [rurseekatze/node-tileserver#149]
Recent issues have no answers
Latest stable release in 2014
Last commit to master in 2018

Is it abandoned?

**Comment by DerDakon** [comment]
OpenRailwayMap is currently switching to a different stack, so this is sort-of abandoned. It works reasonable well, but noone is actively touching it at the moment.

**Comment by undying** [comment]
Which stack OpenRailwayMap switching to?

**Comment by DerDakon** [comment]
Mapnik/Tirex, see https://lists.openrailwaymap.org/pipermail/openrailwaymap/2019-November/000626.html
