### ISSUE TITLE
C++-style comments are not supported

### ISSUE THREAD

**Issue by DerDakon** [rurseekatze/node-tileserver#25]
// should start a comment to the end of the line.

**Comment by rurseekatze** [comment]
C++-style comments starting with `//` are not allowed in (Map)CSS. See https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation#GeneralStructure.

**Comment by DerDakon** [comment]
https://wiki.openstreetmap.org/wiki/MapCSS/0.2#Language_Structure

**Comment by rurseekatze** [comment]
OK, I did not know that. Changed the label to enhancement, but this issue has a low priority.
