### ISSUE TITLE
Asian characters are not shown on map

### ISSUE THREAD

**Issue by rurseekatze** [rurseekatze/node-tileserver#72]
(Moved issue https://github.com/rurseekatze/OpenRailwayMap/issues/408 by @sb12 over to this repository)

Asian characters like Korean, Japanese or Chinese in station names are not shown on the map

Examples:
- [Seoul, Korea](http://www.openrailwaymap.org/?lang=en&lat=37.55304948654156&lon=126.99203968048096&zoom=14&style=standard)
- [Tokyo, Japan](http://www.openrailwaymap.org/?lang=en&lat=35.706551648963575&lon=139.77308750152588&zoom=14&style=standard)
- [Beijing, China](http://www.openrailwaymap.org/?lang=en&lat=39.909834989900844&lon=116.44258975982667&zoom=14&style=standard)

**Comment by rurseekatze** [comment]
That problem seems to occur only on the server side. Tiles that are rendered by the browser show the characters correctly.

Example: http://www.openrailwaymap.org/canvas.php?lang=en&lat=37.55304948654156&lon=126.99203968048096&zoom=14&style=standard

**Comment by DerDakon** [comment]
Install baekmuk fonts?

**Comment by DerDakon** [comment]
Seems to fixed with the new server, so it was probably some font software missing somewhere down the stack.

**Comment by rurseekatze** [comment]
No code fixes are necessary here. Just install font packages and change the font properties in MapCSS stylesheets.
